// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BazaAudyt.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250607142128_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BazaAudyt.Models.CzlonkowieZespolu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CzyAdmin")
                        .HasColumnType("bit");

                    b.Property<bool>("CzyAudytor")
                        .HasColumnType("bit");

                    b.Property<string>("Imie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inicjaly")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NazwaUzytkownika")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazwisko")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Warstwa")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CzlonkowieZespolu");
                });

            modelBuilder.Entity("BazaAudyt.Models.Konta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Konta");
                });

            modelBuilder.Entity("BazaAudyt.Models.LPA_PlanAudytow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AudytorId")
                        .HasColumnType("int");

                    b.Property<string>("Audytowany")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Brygada")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Data")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataPlanowana")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataZamkniecia")
                        .HasColumnType("datetime2");

                    b.Property<string>("Komentarz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObszarAudytu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pozycja")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Stanowisko")
                        .HasColumnType("int");

                    b.Property<string>("Towarzyszacy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Wydzial")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LPA_PlanAudytow");
                });

            modelBuilder.Entity("BazaAudyt.Models.LPA_PodsumowanieWynikow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Audytowany")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DataWykonania")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdAudytowanego")
                        .HasColumnType("int");

                    b.Property<int?>("IdAudytu")
                        .HasColumnType("int");

                    b.Property<int?>("IdCzesci")
                        .HasColumnType("int");

                    b.Property<string>("Komentarz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Rozpoczety")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("LPA_PodsumowanieWynikow");
                });

            modelBuilder.Entity("BazaAudyt.Models.LPA_Pytania", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktywne")
                        .HasColumnType("bit");

                    b.Property<string>("Norma")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Nr")
                        .HasColumnType("int");

                    b.Property<string>("Obszar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pytanie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Waga")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("LPA_Pytania");
                });

            modelBuilder.Entity("BazaAudyt.Models.LPA_Wyniki", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("IdAudytu")
                        .HasColumnType("int");

                    b.Property<string>("Komentarz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pytanie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uwagi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Wartosc")
                        .HasColumnType("int");

                    b.Property<string>("Wynik")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LPA_Wyniki");
                });

            modelBuilder.Entity("BazaAudyt.Models.StanowiskoPracy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Gniazdo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdLidera")
                        .HasColumnType("int");

                    b.Property<int?>("NrGniazda")
                        .HasColumnType("int");

                    b.Property<string>("ObszarLPA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Proces")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RodzajStanowiska")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Typ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Wydzial")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StanowiskaPracy");
                });
#pragma warning restore 612, 618
        }
    }
}
